package game;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

public class TitleScreenController {
	@FXML
	private Button playButton;
	@FXML
	private Button infoButton;
	@FXML
	private Button menuButton;
	@FXML
	private Button quitButton;

	// Event Listener on Button[#playButton].onAction
	@FXML
	public void playerSelection(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#infoButton].onAction
	@FXML
	public void infoScreen(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#menuButton].onAction
	@FXML
	public void mainMenu(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#quitButton].onAction
	@FXML
	public void exit(ActionEvent event) {
		// TODO Autogenerated
	}
}
