package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.layout.BorderPane;
import javafx.stage.Stage;
import javafx.application.Application;
import javafx.event.ActionEvent;

public class MainMenu extends Application {
	@FXML
	private Button quitApplication;
	@FXML
	private Button pong;
	@FXML
	private Button simon;
	@FXML
	private Button snake;
	@FXML
	private Button jumper;
	@FXML
	private Button shooter;
	@FXML
	private Button spaceInvaders;

	public static void run(String[] args) {
		launch(args);
	}
	
	@Override
	public void start(Stage primaryStage) throws Exception {
		try {
			BorderPane root = FXMLLoader.load(getClass().getResource("MainMenu.fxml"));
			Scene scene = new Scene(root);
			scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
			String title = "MCC Arcade";
			ArcadeView.setScene(scene, title);
			ArcadeView.showStage();

		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	// Event Listener on Button[#quitApplication].onAction
	@FXML
	public void exitApplication(ActionEvent event) {
		System.exit(0);
	}

	// Event Listener on Button[#pong].onAction
	@FXML
	public void startPong(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button[#simon].onAction
	@FXML
	public void startSimon(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button[#snake].onAction
	@FXML
	public void startSnake(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button[#jumper].onAction
	@FXML
	public void startJumper(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button[#shooter].onAction
	@FXML
	public void startShooter(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button[#spaceInvaders].onAction
	@FXML
	public void startSpaceInvaders(ActionEvent event) {
		// TODO Autogenerated
	}

}
