package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

public class MainMenu {
	@FXML
	private Button quitApplication;
	@FXML
	private Button pong;
	@FXML
	private Button simon;
	@FXML
	private Button snake;
	@FXML
	private Button jumper;
	@FXML
	private Button shooter;
	@FXML
	private Button spaceInvaders;

	// Event Listener on Button[#quitApplication].onAction
	@FXML
	public void exitApplication(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#pong].onAction
	@FXML
	public void startPong(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#simon].onAction
	@FXML
	public void startSimon(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#snake].onAction
	@FXML
	public void startSnake(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#jumper].onAction
	@FXML
	public void startJumper(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#shooter].onAction
	@FXML
	public void startShooter(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#spaceInvaders].onAction
	@FXML
	public void startSpaceInvaders(ActionEvent event) {
		// TODO Autogenerated
	}
}
